version: '3'
services:
  backend-server-scheduler:
    image: tomcat:9
    volumes:
      - "./target/scheduler-service.war:/usr/local/tomcat/webapps/scheduler-service.war"
    restart: always
  backend-server-normal:
    image: tomcat:9
    volumes:
      - "./target/scheduler-service.war:/usr/local/tomcat/webapps/scheduler-service.war"
    deploy:
      replicas: 2
    restart: always
  load-balancer:
    image: nginx
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - backend-server-scheduler
      - backend-server-normal
    restart: always
    ports:
      - "7000:80"